#!/bin/zsh
source ~/.zshrc

BASE=$1
CASE=$2
CASE_=$(sed 's/_/-/g' <<< $CASE)

if [[ ! (-d ./tmp) ]]; then
    git clone git@github.com:Baaaaam/FCO.git ./tmp
fi
cd tmp

git checkout ${BASE}_${CASE}
#rm cyclus.sqlite; cyclus main.xml
cyan -db cyclus.sqlite trans > ${BASE}_${CASE_}.trans
cyan -db cyclus.sqlite trans -nucs=239Pu > ${BASE}_${CASE_}.trans.pu9
cyan -db cyclus.sqlite trans -nucs=238Pu,239Pu,240Pu,241Pu,242Pu > ${BASE}_${CASE_}.trans.pu
cyan -db cyclus.sqlite trans -nucs=238U > ${BASE}_${CASE_}.trans.u8
cyan -db cyclus.sqlite trans -nucs=233u,234u,235u,236u,237u,238u > ${BASE}_${CASE_}.trans.u


cyan -db cyclus.sqlite inv J1_second_storage_pu > ${BASE}_${CASE_}.inv
cyan -db cyclus.sqlite inv J1_second_storage_pu -nucs=239Pu > ${BASE}_${CASE_}.inv.pu9
cyan -db cyclus.sqlite inv J1_second_storage_pu -nucs=238Pu,239Pu,240Pu,241Pu,242Pu > ${BASE}_${CASE_}.inv.pu
cyan -db cyclus.sqlite inv J1_second_storage_pu -nucs=238U > ${BASE}_${CASE_}.inv.u8
cyan -db cyclus.sqlite inv J1_second_storage_pu -nucs=233u,234u,235u,236u,237u,238u > ${BASE}_${CASE_}.inv.u
