#!/bin/zsh
source ~/.zshrc

BASE=$1
CASE=$2
CASE_=$(sed 's/_/-/g' <<< $CASE)

#if [[ ! (-d ./tmp) ]]; then
#    mkdir ./tmp
#fi
cd tmp
#rm -rf ${BASE}_${CASE}
#git clone git@github.com:Baaaaam/EG29.git ./${BASE}_${CASE}
cd ${BASE}_${CASE}
#
#git fetch origin
#git checkout ${BASE}
#git checkout ${BASE}_${CASE}
#rm cyclus.sqlite; cyclus main.xml -v2

cyan -db cyclus.sqlite trans > ${BASE}_${CASE_}.trans
cyan -db cyclus.sqlite trans -nucs=238Pu > ${BASE}_${CASE_}.trans.pu8
cyan -db cyclus.sqlite trans -nucs=239Pu > ${BASE}_${CASE_}.trans.pu9
cyan -db cyclus.sqlite trans -nucs=240Pu > ${BASE}_${CASE_}.trans.pu10
cyan -db cyclus.sqlite trans -nucs=241Pu > ${BASE}_${CASE_}.trans.pu11
cyan -db cyclus.sqlite trans -nucs=242Pu > ${BASE}_${CASE_}.trans.pu12
cyan -db cyclus.sqlite trans -nucs=241Am > ${BASE}_${CASE_}.trans.am11
cyan -db cyclus.sqlite trans -nucs=238Pu,239Pu,240Pu,241Pu,242Pu,241Am > ${BASE}_${CASE_}.trans.pu
cyan -db cyclus.sqlite trans -nucs=235U > ${BASE}_${CASE_}.trans.u5
cyan -db cyclus.sqlite trans -nucs=238U > ${BASE}_${CASE_}.trans.u8
cyan -db cyclus.sqlite trans -nucs=233u,234u,235u,236u,237u,238u > ${BASE}_${CASE_}.trans.u

cyan -db cyclus.sqlite inv J1_second_storage_pu > ${BASE}_${CASE_}.inv
cyan -db cyclus.sqlite inv -nucs=238Pu J1_second_storage_pu > ${BASE}_${CASE_}.inv.pu8
cyan -db cyclus.sqlite inv -nucs=239Pu J1_second_storage_pu > ${BASE}_${CASE_}.inv.pu9
cyan -db cyclus.sqlite inv -nucs=240Pu J1_second_storage_pu > ${BASE}_${CASE_}.inv.pu10
cyan -db cyclus.sqlite inv -nucs=241Pu J1_second_storage_pu > ${BASE}_${CASE_}.inv.pu11
cyan -db cyclus.sqlite inv -nucs=242Pu J1_second_storage_pu > ${BASE}_${CASE_}.inv.pu12
cyan -db cyclus.sqlite inv -nucs=241Pu J1_second_storage_pu > ${BASE}_${CASE_}.inv.am11
cyan -db cyclus.sqlite inv -nucs=238Pu,239Pu,240Pu,241Pu,242Pu,241Am J1_second_storage_pu > ${BASE}_${CASE_}.inv.pu
cyan -db cyclus.sqlite inv -nucs=235U J1_second_storage_pu > ${BASE}_${CASE_}.inv.u5
cyan -db cyclus.sqlite inv -nucs=238U J1_second_storage_pu > ${BASE}_${CASE_}.inv.u8
cyan -db cyclus.sqlite inv -nucs=233u,234u,235u,236u,237u,238u J1_second_storage_pu > ${BASE}_${CASE_}.inv.u


mv EG29_Case*trans* /Users/mouginot/work/FCO/EG29/analyse_case1/data
mv EG29_Case*inv* /Users/mouginot/work/FCO/EG29/analyse_case1/data
