#!/bin/zsh
source ~/.zshrc

./dat_gene EG29_Case.3.1 MF
./dat_gene EG29_Case.3.2 MF
./dat_gene EG29_Case.3.3 MF 

python run.py

cd processed_data
for file in `ls 1* 2* 3*`; do
    python ../convert_m2y.py $file y_$file
done

python run2.py
	    
